---
title: "Transect POC and PON data package generated using EMLassemblyline and ediutilities"
author: "Joe Futrelle, Kate Morkeski"
date: "2023-03-16"
output: html_notebook
---

Libraries used

```{r}
# two of the required packages are installed from GitHub
# library(remotes)
# remotes::install_github("EDIorg/EMLassemblyline")
# remotes::install_github("WHOIGit/ediutilities")

library(EMLassemblyline)
library(ediutilities)
library(here)
library(lubridate)
library(dplyr)

```

Read data table

```{r}
data_table <- read.csv(here('nes-lter-poc-transect-input.csv'))
data_table$date_time_utc = ymd_hms(data_table$date)
data_table <- data_table |> arrange(date_time_utc)
write.csv(data_table,'nes-lter-poc-transect.csv', na = "NaN", row.names=FALSE)

```

Read the Excel metadata template and generate text templates used by
EMLassemblyline

```{r}
excel_to_template(here('nes-lter-poc-transect-info'), 'nes-lter-poc-transect', rights='CC0', file.type = ".md")
#excel_to_template(here('nes-lter-poc-transect-info'), 'nes-lter-poc-transect', rights='CC0')
```
Generate the package and insert the parent project node into the resulting EML

```{r}
# add package ID
pkg_id <- 'knb-lter-nes.27.3'

make_eml(here(),
         dataset.title='Particulate organic carbon (POC) and nitrogen (PON) from Northeast U.S. Shelf Long Term Ecological Research (NES-LTER) Transect cruises, ongoing since 2017',
         data.table='nes-lter-poc-transect.csv',
         data.table.description='NES-LTER transect POC and PON data',
         data.table.name = 'nes-lter-poc-transect',
         temporal.coverage = temporal_coverage(data_table$date),
         geographic.description = "NES-LTER Transect",
         geographic.coordinates = geographic_coordinates(data_table$latitude, data_table$longitude),
         maintenance.description = "ongoing",
         user.id = "NES",
         user.domain = "LTER",
         package.id = pkg_id)

project_insert(pkg_id, "parent_project_NESI-II_RAPID.txt")

```
